### ISSUE TITLE
Overslaan tekst met ###

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/tscan#19]
Op dit moment accepteert T-Scan via bestandenlijsten geen teksten die beginnen met overgeslagen tekst. Het probleem is dus erger geworden.

**Comment by oktaal** [comment]
@pandermaat ik kan dit probleem niet nabootsen?

Ik heb geprobeerd:

- met/zonder BOM (Windows-formaat)
- met/zonder witregel aan het begin van het bestand

In alle gevallen wordt commentaar aan het begin van het bestand netjes weggefilterd.

**Comment by pandermaat** [comment]
Dag Sheean,

Ik heb het probleem  ook niet meer gezien de laatste weken. Ik denk dat het eerder is opgelost, in combinatie met die BOM-kwestie denk ik.
Fijn dus.

Groet van Henk
________________________________
Van: Sheean Spoel ***@***.***>
Verzonden: donderdag 17 juni 2021 14:40
Aan: UUDigitalHumanitieslab/tscan ***@***.***>
CC: Pander Maat, H.L.W. (Henk) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [UUDigitalHumanitieslab/tscan] Overslaan tekst met ### (#19)


@pandermaat<https://github.com/pandermaat> ik kan dit probleem niet nabootsen?

Ik heb geprobeerd:

  *   met/zonder BOM (Windows-formaat)
  *   met/zonder witregel aan het begin van het bestand

In alle gevallen wordt commentaar aan het begin van het bestand netjes weggefilterd.
